### ISSUE TITLE
Criteria for evaluating CD event requests

### ISSUE THREAD

**Issue by brianking** [mozilla/connected-devices#2]
We are seeing more and more event requests by Mozillians, Reps and others. In order to better evaluate the requests, let's define a list of criteria for an event to be approved.

**Comment by brianking** [comment]
Started a doc to hack on:

https://docs.google.com/document/d/1pYK5O8oyyX4VSjiIw45WB3SUI9OxshPIcFl8_knhFbc/edit?usp=sharing

/cc @autonome

**Comment by brianking** [comment]
@mikehenrty as soon as you make a pass on the doc, I will move it to the wiki. From there, we can solicit feedback and more contributions.

**Comment by mikehenrty** [comment]
R+ from me. Made a few notes and changes.

**Comment by nataliamoz** [comment]
We can add co-creation workshops where
- users are involved in brainstorms (idea generation) 
- users tell their experience with products (needs, behaviours, painpoints...) 
- product teams listen to users
- users enhance early concepts / prototypes

**Comment by brianking** [comment]
First version up at:
https://wiki.mozilla.org/Connected_Devices/Participation/Events/Evaluation

**Comment by ioana-chiorean** [comment]
Hey guys, is this something you would consider share with the Reps in one of the calls?
Lately we opened up the audience for it to all mozillians ( specially for those in the Participation Cohort)

📆 🎤 
cc @couci

**Comment by brianking** [comment]
@ioana-chiorean sure, but I don't think we are ready yet. Related to your request also in issue #7 we will wait a couple of weeks at least until the toolkit is filled out a bit more and then we will talk about everything together.

**Comment by ioana-chiorean** [comment]
🎉 yes, cool! I it not intended for this week but to keep it in your minds for when is ready! 💃
