### ISSUE TITLE
[MozLondon] Run post-event survey

### ISSUE THREAD

**Issue by brianking** [mozilla/connected-devices#4]
We will survey our CD volunteers to dive deeper and get some hard data on what worked and what didn't work.
- Brian to ask Francisco for template
- Brian and Michael to adapt and form questions
- Gather feedback from other stakeholders (Rina and Valerie) 
- Michael to distribute

**Comment by brianking** [comment]
@mikehenrty I just talked to @couci about a template. The Participation team is sending out a survey to all volunteers by end of week. One option is that we add in our questions to that one, and they only show for CD volunteers. I think we should go with that, I don't see us having many questions, unless you see more value of us doing our own survey.

**Comment by mikehenrty** [comment]
That works for me. Thanks!

**Comment by brianking** [comment]
Gathering questions here:

https://docs.google.com/a/mozilla.com/document/d/1fasGAmd9fX2gdi9aOKlFsDHJMaC6JetGUdqoZEj4wtw/edit?usp=sharing
