### ISSUE TITLE
Please add a LICENSE file to this repository.

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/connected-devices#5]
This repository is becoming a source of information for the c-d project, as evidenced by (at the very least) the Github issues. Please add a LICENSE file to this public repository - whether MPL2 (for code) or CC-BY-SA (for website content) or some other less-common choice - or make the repository private, if its contents are not meant to be used by the community at large.

(I understand this is a new repository and there's very little content so far, but it's still a public repository with a closed "All rights reserved" license until we publish a LICENSE file indicating otherwise.)

No rush on this, just filing since I noticed.

**Comment by mikehenrty** [comment]
Good call @floatingatoll, I'll add the MPL2 since we are planning on having both content and code in this repo.
