### ISSUE TITLE
First Draft of Toolkit for CD Particiaption

### ISSUE THREAD

**Issue by brianking** [mozilla/connected-devices#7]
Self-serve toolkit that:
- provides a guide run design/ideation workshops with your communities
- compiles links to relevant CD resources
- provides guidelines for running events, in terms of criteria to evaluate and expected outcomes

Initial developer events toolkit ideas from Natalia:
https://docs.google.com/a/mozilla.com/document/d/1ypl1vkSfEdw65pacwM8jnLYURxIxp26QNuA65wTg0eM/edit?usp=sharing

**Comment by mikehenrty** [comment]
First draft here:
http://mozilla.github.io/connected-devices/site/getting-started.html

**Comment by ioana-chiorean** [comment]
Hey guys, is this something you would consider share with the Reps in one of the calls? 
Lately we opened up the audience for it to all mozillians ( specially for those in the Participation Cohort)  👓 🎤 📞 📆 
cc @couci
